# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Event ID')),
                ('retry_policy', models.TextField(verbose_name='Retry Policy')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook', models.URLField(verbose_name='Web Hook URL')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventful_django.Event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('webhook', 'event')]),
        ),
    ]
