# Generated by Django 2.0.7 on 2019-01-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='headers',
            field=models.TextField(null=True, verbose_name='Request Headers'),
        ),
    ]
