# Generated by Django 2.0.7 on 2019-09-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventful_django', '0002_subscription_headers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPubSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('headers', models.TextField(null=True, verbose_name='Request Headers')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventful_django.Event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionpubsub',
            unique_together={('topic', 'event')},
        ),
    ]
