# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-12-05 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful_django', '0003_auto_20190919_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionpubsub',
            name='headers',
        ),
        migrations.AddField(
            model_name='subscriptionpubsub',
            name='gcp_project_id',
            field=models.CharField(default='extended-web-217714', max_length=100),
        ),
    ]
