# Generated by Django 2.0.7 on 2020-06-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful_django', '0004_auto_20191205_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='client_email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_cloud_function',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='private_key',
            field=models.TextField(null=True, verbose_name='Private Key'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='token_uri',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
